#!/usr/bin/env bash
# Shows "To infinity and beyond" with sleep 2
# Shows "I am invincible!!!" in between each iteration

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible!!!"' SIGTERM
done
